#!/usr/bin/env python3
"""
train_stage_a.py — YOLOv8n fish detector training script (Stage A)

Stage A classifies each photo into one of five categories:
  0: whole_fish  — complete fish visible
  1: lure        — fishing lure, no fish
  2: fish_part   — partial fish (tail, fin, etc.)
  3: fry         — small juvenile fish / fry
  4: no_fish     — background, hands, water, gear

Model choice — YOLOv8n (nano):
  - Best speed/accuracy tradeoff for single-dominant-object images (not dense detection)
  - ~5 ms/image on CPU — critical for Telegram bot latency
  - Robust to noisy fishing photos: variable lighting, motion blur, cluttered backgrounds
  - ultralytics handles all augmentation: mosaic, mixup, HSV jitter, flip
  - COCO-pretrained weights transfer well to the fishing domain

Usage:
    python3 scripts/train_stage_a.py [--epochs 100] [--batch 16] [--device cpu]
"""

import argparse
import json
import shutil
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# Repo root is always the parent of this script's directory
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_ROOT = REPO_ROOT / "data"
MODELS_DIR = DATA_ROOT / "fish_models"
LABELED_DIR = DATA_ROOT / "fish_dataset" / "stage_a" / "labeled"
CONFIGS_DIR = REPO_ROOT / "configs"
YAML_PATH = CONFIGS_DIR / "fish_detect.yaml"

CLASS_NAMES_A = {
    "0": "whole_fish",
    "1": "lure",
    "2": "fish_part",
    "3": "fry",
    "4": "no_fish",
}

MIN_TRAIN_IMAGES = 10


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _banner(msg: str) -> None:
    print(f"\n{'=' * 60}")
    print(f"  {msg}")
    print(f"{'=' * 60}")


def _ok(msg: str) -> None:
    print(f"[OK]  {msg}")


def _fail(msg: str) -> None:
    print(f"[FAIL] {msg}", file=sys.stderr)


def _info(msg: str) -> None:
    print(f"[INFO] {msg}")


# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------

def check_ultralytics() -> None:
    """Ensure ultralytics is installed and importable."""
    try:
        import ultralytics  # noqa: F401
        _ok(f"ultralytics {ultralytics.__version__} is installed")
    except ImportError:
        _fail("ultralytics is not installed.")
        _fail("Install it with:  pip install ultralytics")
        sys.exit(1)


def check_labeled_data() -> None:
    """Ensure the training image directory exists and has enough images."""
    train_images = LABELED_DIR / "train" / "images"
    if not train_images.exists():
        _fail(f"Training images directory not found: {train_images}")
        _fail("Expected structure:")
        _fail("  data/fish_dataset/stage_a/labeled/train/images/")
        _fail("  data/fish_dataset/stage_a/labeled/val/images/")
        sys.exit(1)

    image_exts = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
    images = [p for p in train_images.iterdir() if p.suffix.lower() in image_exts]
    count = len(images)

    if count < MIN_TRAIN_IMAGES:
        _fail(
            f"Too few training images: found {count}, need at least {MIN_TRAIN_IMAGES}."
        )
        _fail(f"Directory: {train_images}")
        sys.exit(1)

    _ok(f"Found {count} training images in {train_images}")

    # Also check val split exists (warn but don't abort)
    val_images = LABELED_DIR / "val" / "images"
    if not val_images.exists():
        print(
            f"[WARN] Validation directory missing: {val_images}\n"
            "       YOLO training will proceed but validation metrics won't be reported.",
            file=sys.stderr,
        )
    else:
        val_count = len([p for p in val_images.iterdir() if p.suffix.lower() in image_exts])
        _ok(f"Found {val_count} validation images in {val_images}")


def check_models_dir() -> None:
    """Create data/fish_models/ if it doesn't exist."""
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    _ok(f"Models directory ready: {MODELS_DIR}")


# ---------------------------------------------------------------------------
# YAML generation
# ---------------------------------------------------------------------------

def generate_yaml() -> None:
    """Write configs/fish_detect.yaml with the absolute path to labeled data."""
    CONFIGS_DIR.mkdir(parents=True, exist_ok=True)

    labeled_abs = str(LABELED_DIR.resolve())

    yaml_content = textwrap.dedent(f"""\
        # fish_detect.yaml — YOLOv8 dataset config for Stage A fish detector
        # Auto-generated by train_stage_a.py — do not edit path manually.
        #
        # Classes:
        #   0: whole_fish  — complete fish visible
        #   1: lure        — fishing lure / tackle, no fish
        #   2: fish_part   — partial fish (tail, fin, head fragment)
        #   3: fry         — juvenile fish / fry
        #   4: no_fish     — background, hands, water, gear

        path: {labeled_abs}
        train: train/images
        val: val/images
        test: test/images

        nc: 5

        names:
          0: whole_fish
          1: lure
          2: fish_part
          3: fry
          4: no_fish
    """)

    YAML_PATH.write_text(yaml_content, encoding="utf-8")
    _ok(f"Generated {YAML_PATH}")
    _info(f"  dataset path -> {labeled_abs}")


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train(epochs: int, batch: int, device: str) -> "ultralytics.engine.results.Results":
    """Run YOLO training and return the results object."""
    from ultralytics import YOLO  # import deferred until after checks

    _banner(f"Training YOLOv8n — {epochs} epochs, batch={batch}, device={device}")

    model = YOLO("yolov8n.pt")  # downloads pretrained COCO weights if not cached

    results = model.train(
        data=str(YAML_PATH),
        epochs=epochs,
        imgsz=640,
        batch=batch,
        patience=20,                  # early stopping — stops if no mAP improvement for 20 epochs
        project=str(DATA_ROOT / "runs"),
        name="fish_detector",
        exist_ok=True,
        device=device,
        # ------------------------------------------------------------------
        # Augmentation tuned for fishing-photo characteristics:
        # ------------------------------------------------------------------
        hsv_h=0.015,    # hue jitter — fish vary in colour (silver, green, brown)
        hsv_s=0.7,      # saturation jitter — wet vs dry fish, different lighting
        hsv_v=0.4,      # value jitter — outdoor shooting with changing daylight
        flipud=0.0,     # vertical flip disabled — fish are not presented upside-down
        fliplr=0.5,     # horizontal flip — symmetric for fish held either way
        mosaic=1.0,     # mosaic augmentation — helps detect fish in complex scenes
        degrees=15.0,   # rotation — fish are often held at angles
        translate=0.1,  # translation
        scale=0.5,      # scale jitter — fish size varies greatly
        shear=0.0,      # shear disabled — unrealistic for fishing photos
        perspective=0.0,# perspective disabled — not useful here
        # ------------------------------------------------------------------
        # Class loss weight — balance classifier vs box regression
        # ------------------------------------------------------------------
        cls=0.5,
        verbose=True,
    )

    return results


# ---------------------------------------------------------------------------
# Post-training steps
# ---------------------------------------------------------------------------

def copy_best_model(run_dir: Path) -> Path:
    """Copy best.pt from YOLO run to data/fish_models/detector_v1.pt."""
    best_pt = run_dir / "weights" / "best.pt"
    if not best_pt.exists():
        # Fallback to last.pt if best wasn't saved (can happen with very short runs)
        best_pt = run_dir / "weights" / "last.pt"
    if not best_pt.exists():
        _fail(f"Could not find model weights in {run_dir / 'weights'}")
        sys.exit(1)

    dest = MODELS_DIR / "detector_v1.pt"
    shutil.copy2(best_pt, dest)
    _ok(f"Copied {best_pt.name} -> {dest}")
    return dest


def validate_inference(model_path: Path) -> None:
    """Run inference on one training image to verify the saved model loads correctly."""
    from ultralytics import YOLO

    _info("Validating saved model with single-image inference...")

    train_images = LABELED_DIR / "train" / "images"
    image_exts = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
    sample = next(
        (p for p in train_images.iterdir() if p.suffix.lower() in image_exts),
        None,
    )
    if sample is None:
        print("[WARN] No training image found for inference validation — skipping.", file=sys.stderr)
        return

    model = YOLO(str(model_path))
    preds = model(str(sample), verbose=False)
    _ok(f"Inference OK — {len(preds[0].boxes)} detection(s) on {sample.name}")


def write_class_names() -> None:
    """Write class_names_a.json to the models directory."""
    dest = MODELS_DIR / "class_names_a.json"
    dest.write_text(json.dumps(CLASS_NAMES_A, indent=2, ensure_ascii=False), encoding="utf-8")
    _ok(f"Wrote {dest}")


def update_metadata(metrics: dict) -> None:
    """Merge Stage A metrics into data/fish_models/metadata.json."""
    from datetime import datetime, timezone

    meta_path = MODELS_DIR / "metadata.json"
    if meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            meta = {}
    else:
        meta = {}

    meta.setdefault("detector", {})
    meta["detector"].update(
        {
            "backend": "yolov8n",
            "trained_at": datetime.now(timezone.utc).isoformat(),
            "dataset_size": {
                "train": len(list((LABELED_DIR / "train" / "images").glob("*")))
                if (LABELED_DIR / "train" / "images").exists()
                else 0,
                "val": len(list((LABELED_DIR / "val" / "images").glob("*")))
                if (LABELED_DIR / "val" / "images").exists()
                else 0,
                "test": len(list((LABELED_DIR / "test" / "images").glob("*")))
                if (LABELED_DIR / "test" / "images").exists()
                else 0,
            },
            "metrics": metrics,
        }
    )

    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    _ok(f"Updated {meta_path}")


def print_metrics(results) -> dict:
    """Extract and print final training metrics. Returns dict for metadata."""
    _banner("Final Training Metrics")

    metrics_dict: dict = {}

    try:
        # results.results_dict is populated after model.train() completes
        rd = results.results_dict
        map50 = rd.get("metrics/mAP50(B)", rd.get("metrics/mAP50", None))
        map50_95 = rd.get("metrics/mAP50-95(B)", rd.get("metrics/mAP50-95", None))

        if map50 is not None:
            print(f"  mAP@0.5       : {map50:.4f}")
            metrics_dict["mAP50"] = round(float(map50), 4)
        if map50_95 is not None:
            print(f"  mAP@0.5-0.95  : {map50_95:.4f}")
            metrics_dict["mAP50_95"] = round(float(map50_95), 4)

        # Per-class precision / recall from the validator
        try:
            validator = results.validator
            if validator is not None and hasattr(validator, "metrics"):
                vm = validator.metrics
                names = vm.names if hasattr(vm, "names") else CLASS_NAMES_A
                print("\n  Per-class metrics:")
                print(f"  {'Class':<15} {'Precision':>10} {'Recall':>10}")
                print(f"  {'-'*37}")
                for i, name in names.items() if hasattr(names, "items") else enumerate(names):
                    try:
                        p = float(vm.box.p[i])
                        r = float(vm.box.r[i])
                        print(f"  {name:<15} {p:>10.4f} {r:>10.4f}")
                        metrics_dict[f"precision_{name}"] = round(p, 4)
                        metrics_dict[f"recall_{name}"] = round(r, 4)
                    except (IndexError, AttributeError):
                        pass
        except Exception as exc:
            _info(f"Per-class metrics unavailable: {exc}")

    except Exception as exc:
        _info(f"Could not extract detailed metrics: {exc}")
        _info("Check data/runs/fish_detector/ for full CSV logs and charts.")

    return metrics_dict


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train YOLOv8n fish detector (Stage A)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--epochs", type=int, default=100, help="Number of training epochs")
    parser.add_argument("--batch", type=int, default=16, help="Batch size")
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Training device: 'cpu', '0' (GPU 0), 'mps' (Apple Silicon)",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    _banner("Stage A — YOLOv8n Fish Detector Training")
    _info(f"Repo root : {REPO_ROOT}")
    _info(f"Epochs    : {args.epochs}")
    _info(f"Batch     : {args.batch}")
    _info(f"Device    : {args.device}")

    # ---- Prerequisites ----
    _banner("Prerequisite Checks")
    check_ultralytics()
    check_labeled_data()
    check_models_dir()

    # ---- Generate YAML ----
    _banner("Generating Dataset Config")
    generate_yaml()

    # ---- Train ----
    try:
        results = train(args.epochs, args.batch, args.device)
    except KeyboardInterrupt:
        print("\n[INTERRUPTED] Training interrupted by user.", file=sys.stderr)
        print("Partial run saved in data/runs/fish_detector/", file=sys.stderr)
        print("Re-run with the same command to resume (exist_ok=True).", file=sys.stderr)
        sys.exit(1)
    except Exception as exc:
        _fail(f"Training failed: {exc}")
        raise  # show full traceback

    # ---- Locate run directory ----
    run_dir = DATA_ROOT / "runs" / "fish_detector"

    # ---- Post-training ----
    _banner("Post-Training Steps")
    dest_model = copy_best_model(run_dir)
    validate_inference(dest_model)
    write_class_names()

    metrics = print_metrics(results)
    update_metadata(metrics)

    _banner("Done")
    _ok(f"Model   -> {MODELS_DIR / 'detector_v1.pt'}")
    _ok(f"Classes -> {MODELS_DIR / 'class_names_a.json'}")
    _ok(f"Meta    -> {MODELS_DIR / 'metadata.json'}")
    print()


if __name__ == "__main__":
    main()
